version: '3.8'

services:
  # --- SERVICE DATABASE (PostgreSQL) ---
  db:
    image: postgres:15-alpine
    container_name: iot_postgres
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - "5432:5432"
    # Healthcheck: Dokter yang ngecek DB sudah siap belum
    healthcheck:
      # KOREKSI: Pakai variabel environment biar sinkron sama .env
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: iot_redis
    restart: always
    ports:
      - "6379:6379"

  # --- SERVICE BACKEND (FastAPI) ---
  web:
    # KOREKSI 1: Matikan build manual, kita pakai Image dari GitHub
    # build: .
    
    # KOREKSI 2: Ganti username_github jadi username asli
    image: ghcr.io/bagus-devlab/pcb-backend-api:latest
    
    container_name: iot_fastapi
    restart: always
    
    # KOREKSI 3: Hilangkan --reload untuk production (biar enteng)
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000
    
    environment:
      - REDIS_URL=redis://redis:6379/0
    
    # KOREKSI 4: Matikan mounting volume code, biar dia pake code yg ada di dalam Image
    # volumes:
    #   - ./app:/code/app
    
    ports:
      # KOREKSI 5: Host Port ganti 8006 (karena 8000 dipake Portainer)
      - "8006:8000"
      
    env_file:
      - .env
      
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started

volumes:
  postgres_data: