version: '3.8'

networks:
  default:
    driver: bridge

services:
  # --- SERVICE DATABASE (PostgreSQL) ---
  db:
    image: postgres:15-alpine
    container_name: iot_postgres
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data:z
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - "5432:5432"
    healthcheck:
      # Menggunakan user yang benar (iot_postgres) agar healthcheck valid
      test: [ "CMD-SHELL", "pg_isready -U ${DB_USER}" ]
      interval: 5s
      timeout: 5s
      retries: 5

  # --- SERVICE REDIS ---
  redis:
    image: redis:7-alpine
    container_name: iot_redis
    restart: always
    ports:
      - "6379:6379"

  # --- SERVICE BACKEND (FastAPI) ---
  web:
    image: ghcr.io/bagus-devlab/pcb-backend-api:latest
    container_name: iot_fastapi
    restart: always
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000
    environment:
      - REDIS_URL=redis://redis:6379/0
    volumes:
      # Ditambahkan :z karena kamu pakai Fedora (SELinux)
      - ./app/serviceAccountKey.json:/code/app/serviceAccountKey.json:z
    ports:
      - "8006:8000"
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started

volumes:
  postgres_data:
